[manager]
linemode = "size"
sort_by = "alphabetical"
sort_dir_first = true
show_hidden = true
[opener]
edit = [
	{ run = 'hx "$@"', block = true },
]
play = [
	{ run = 'mpc add "$@"', orphan = true },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
[preview]
image_quality = 75
sixel_fraction = 10
max_width = 960
max_height = 1600
